POST http://localhost:8088/comment/new
Content-Type:application/json

{
  "cno": "U10M11011.02",
  "cid": 3,
  "sno": "2020303030",
  "time": "2022/12/19",
  "detail": "老师人实在是太好了，人美心善给分高，讲课耐心认真",
  "isselect": 1,
  "sscore": 98,
  "visible": 0
}
