POST http://localhost:8088/course/update
Content-Type:application/json

{
  "cno": "114514",
  "cname": "母猪的产后护理",
  "tname": "yyh",
  "dname": "计算机学院",
  "cclf": "文化素养课程",
  "credit": "114",
  "description": "这是一次更新的测试"
}